#!/usr/bin/env ruby
require 'fileutils'
include FileUtils

APP_ROOT = File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  puts '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')

  system('bin/yarn')

  puts "\n== Copying sample files =="
  unless File.exist?('.env.local')
    cp '.env', '.env.local'
  end

  puts "\n== Preparing database and seeds =="
  system! 'bin/rake dev:prime'

  puts "\n== Removing old logs and tempfiles =="
  system! 'bin/rails log:clear tmp:clear'

  puts "\n== Restarting application server =="
  system! 'bin/rails restart'

  puts "\n== Activating overcommit =="
  system! 'bin/overcommit --install'
end
