#!/bin/sh

# Set up Rails app. Run this script immediately after cloning the codebase.

# Exit if any subcommand fails
set -e

echo '== Installing dependencies =='
gem install bundler --conservative
bundle check || bundle install
bin/yarn

echo "\n== Copying sample files =="
if [ ! -f .env.local ]; then
  cp .env.sample .env.local
fi

echo "\n== Preparing database and seeds =="
bin/rails dev:prime

echo "\n== Activating overcommit =="
bin/overcommit --install
